name: ROS 2 CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test the project
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build and test
        uses: ichiro-its/ros2-ci@v0.3.0
        with:
          pre-build: apt-get update && apt-get install -y python3-pip && pip3 install websockets
